// Acessa os elementos HTML que vamos manipular
const checkboxesContainer = document.getElementById('group-checkboxes');
const updateButton = document.getElementById('update-chart');
const chartCanvas = document.getElementById('sepkoski-chart');
let myChart; // Variável para armazenar a instância do gráfico do Chart.js

// Mapeamento dos estágios para o tempo em milhões de anos (mya)
const TIME_DATA_MYA = {
    "Plei": 2.58, "Plio": 5.33, "Mi": 23.03, "Ol": 33.9, "Eo": 56, "Pale": 66,
    "Maes": 72.1, "Camp": 83.6, "Sant": 86.3, "Coni": 89.8, "Turo": 93.9, "Ceno": 100.5,
    "Albi": 113, "Apti": 125, "Barr": 129.4, "Haut": 132.9, "Vala": 139.8, "Berr": 145,
    "Tith": 152.1, "Kimm": 157.3, "Oxfo": 163.5, "Call": 166.1, "Bath": 168.3, "Bajo": 170.3,
    "Aale": 174.1, "Toar": 182.7, "Plie": 190.8, "Sine": 199.3, "Hett": 201.3, "Nori": 208.5,
    "Carn": 224, "Ladi": 237, "Anis": 242, "Olen": 247.2, "Indu": 251.9, "Tatr": 254.1,
    "Guad": 259.1, "Leon": 264.6, "Sakm": 272.9, "Asse": 290.1, "Step": 295, "Mosc": 303.7,
    "Bash": 307, "Serp": 323.2, "Vise": 346.7, "Tour": 358.9, "Fame": 372.2, "Fras": 382.7,
    "Give": 387.7, "Eife": 393.3, "Emsi": 407.6, "Sieg": 410.8, "Gedi": 419.2, "Prid": 423,
    "Ludl": 425.6, "Wenl": 433.4, "Ldov": 443.8, "Ashg": 458.4, "Cara": 467.3, "Llde": 470,
    "Llvi": 477.7, "Aren": 485.4, "Trem": 488.3, "Trep": 497, "Fran": 500, "Dres": 501,
    "uMid": 504.5, "mMid": 509, "lMid": 514, "Tojo": 517, "Boto": 521, "Atda": 530,
    "Tomm": 541, "N-Da": 541,
    // Dados para os novos itens adicionados
    "Cambriano": 541, "Ordoviciano": 485.4, "Siluriano": 443.8, "Devoniano": 419.2, "Carbonífero": 358.9,
    "Permiano": 298.9, "Triássico": 251.9, "Jurássico": 201.3, "Cretáceo": 145, "Paleogeno": 66,
    "Neogeno": 23.03, "Quaternário": 2.58
};

// Dados de diversidade paleontológica (substituindo o data.json)
const PALEODATA = {
    "paleodata": [
        {
            "name": "Ostracoda",
            "type": "class",
            "diversity_data": [
                { "stage": "Plei", "diversity": 212 }, { "stage": "Plio", "diversity": 228 }, { "stage": "Mi", "diversity": 262 },
                { "stage": "Ol", "diversity": 186 }, { "stage": "Eo", "diversity": 209 }, { "stage": "Pale", "diversity": 141 },
                { "stage": "Maes", "diversity": 142 }, { "stage": "Camp", "diversity": 127 }, { "stage": "Sant", "diversity": 128 },
                { "stage": "Coni", "diversity": 101 }, { "stage": "Turo", "diversity": 99 }, { "stage": "Ceno", "diversity": 108 },
                { "stage": "Albi", "diversity": 96 }, { "stage": "Apti", "diversity": 73 }, { "stage": "Barr", "diversity": 76 },
                { "stage": "Haut", "diversity": 64 }, { "stage": "Vala", "diversity": 59 }, { "stage": "Berr", "diversity": 47 },
                { "stage": "Tith", "diversity": 47 }, { "stage": "Kimm", "diversity": 51 }, { "stage": "Oxfo", "diversity": 55 },
                { "stage": "Call", "diversity": 57 }, { "stage": "Bath", "diversity": 65 }, { "stage": "Bajo", "diversity": 46 },
                { "stage": "Aale", "diversity": 31 }, { "stage": "Toar", "diversity": 35 }, { "stage": "Plie", "diversity": 34 },
                { "stage": "Sine", "diversity": 30 }, { "stage": "Hett", "diversity": 28 }, { "stage": "Nori", "diversity": 25 },
                { "stage": "Carn", "diversity": 21 }, { "stage": "Ladi", "diversity": 22 }, { "stage": "Anis", "diversity": 18 },
                { "stage": "Olen", "diversity": 14 }, { "stage": "Indu", "diversity": 8 }, { "stage": "Tatr", "diversity": 69 },
                { "stage": "Guad", "diversity": 38 }, { "stage": "Leon", "diversity": 48 }, { "stage": "Sakm", "diversity": 49 },
                { "stage": "Asse", "diversity": 52 }, { "stage": "Step", "diversity": 58 }, { "stage": "Mosc", "diversity": 66 },
                { "stage": "Bash", "diversity": 65 }, { "stage": "Serp", "diversity": 86 }, { "stage": "Vise", "diversity": 101 },
                { "stage": "Tour", "diversity": 100 }, { "stage": "Fame", "diversity": 105 }, { "stage": "Fras", "diversity": 107 },
                { "stage": "Give", "diversity": 140 }, { "stage": "Eife", "diversity": 129 }, { "stage": "Emsi", "diversity": 110 },
                { "stage": "Sieg", "diversity": 92 }, { "stage": "Gedi", "diversity": 107 }, { "stage": "Prid", "diversity": 121 },
                { "stage": "Ludl", "diversity": 118 }, { "stage": "Wenl", "diversity": 132 }, { "stage": "Ldov", "diversity": 89 },
                { "stage": "Ashg", "diversity": 170 }, { "stage": "Cara", "diversity": 278 }, { "stage": "Llde", "diversity": 158 },
                { "stage": "Llvi", "diversity": 107 }, { "stage": "Aren", "diversity": 58 }, { "stage": "Trem", "diversity": 3 },
                { "stage": "Trep", "diversity": 1 }, { "stage": "Fran", "diversity": 3 }, { "stage": "Dres", "diversity": 10 },
                { "stage": "uMid", "diversity": 13 }, { "stage": "mMid", "diversity": 33 }, { "stage": "lMid", "diversity": 22 },
                { "stage": "Tojo", "diversity": 18 }, { "stage": "Boto", "diversity": 19 }, { "stage": "Atda", "diversity": 42 },
                { "stage": "Tomm", "diversity": 0 }, { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Trilobita",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 0 }, { "stage": "Plei", "diversity": 0 }, { "stage": "Plio", "diversity": 0 },
                { "stage": "Mi", "diversity": 0 }, { "stage": "Ol", "diversity": 0 }, { "stage": "Eo", "diversity": 0 },
                { "stage": "Pale", "diversity": 0 }, { "stage": "Maes", "diversity": 0 }, { "stage": "Camp", "diversity": 0 },
                { "stage": "Sant", "diversity": 0 }, { "stage": "Coni", "diversity": 0 }, { "stage": "Turo", "diversity": 0 },
                { "stage": "Ceno", "diversity": 0 }, { "stage": "Albi", "diversity": 0 }, { "stage": "Apti", "diversity": 0 },
                { "stage": "Barr", "diversity": 0 }, { "stage": "Haut", "diversity": 0 }, { "stage": "Vala", "diversity": 0 },
                { "stage": "Berr", "diversity": 0 }, { "stage": "Tith", "diversity": 0 }, { "stage": "Kimm", "diversity": 0 },
                { "stage": "Oxfo", "diversity": 0 }, { "stage": "Call", "diversity": 0 }, { "stage": "Bath", "diversity": 0 },
                { "stage": "Bajo", "diversity": 0 }, { "stage": "Aale", "diversity": 0 }, { "stage": "Toar", "diversity": 0 },
                { "stage": "Plie", "diversity": 0 }, { "stage": "Sine", "diversity": 0 }, { "stage": "Hett", "diversity": 0 },
                { "stage": "Nori", "diversity": 0 }, { "stage": "Carn", "diversity": 0 }, { "stage": "Ladi", "diversity": 0 },
                { "stage": "Anis", "diversity": 0 }, { "stage": "Olen", "diversity": 0 }, { "stage": "Indu", "diversity": 0 },
                { "stage": "Tatr", "diversity": 6 }, { "stage": "Guad", "diversity": 20 }, { "stage": "Leon", "diversity": 15 },
                { "stage": "Sakm", "diversity": 15 }, { "stage": "Asse", "diversity": 13 }, { "stage": "Step", "diversity": 15 },
                { "stage": "Mosc", "diversity": 16 }, { "stage": "Bash", "diversity": 22 }, { "stage": "Serp", "diversity": 19 },
                { "stage": "Vise", "diversity": 43 }, { "stage": "Tour", "diversity": 43 }, { "stage": "Fame", "diversity": 40 },
                { "stage": "Fras", "diversity": 25 }, { "stage": "Give", "diversity": 62 }, { "stage": "Eife", "diversity": 147 },
                { "stage": "Emsi", "diversity": 202 }, { "stage": "Sieg", "diversity": 145 }, { "stage": "Gedi", "diversity": 122 },
                { "stage": "Prid", "diversity": 65 }, { "stage": "Ludl", "diversity": 91 }, { "stage": "Wenl", "diversity": 116 },
                { "stage": "Ldov", "diversity": 107 }, { "stage": "Ashg", "diversity": 204 }, { "stage": "Cara", "diversity": 275 },
                { "stage": "Llde", "diversity": 233 }, { "stage": "Llvi", "diversity": 215 }, { "stage": "Aren", "diversity": 236 },
                { "stage": "Trem", "diversity": 226 }, { "stage": "Trep", "diversity": 209 }, { "stage": "Fran", "diversity": 280 },
                { "stage": "Dres", "diversity": 278 }, { "stage": "uMid", "diversity": 286 }, { "stage": "mMid", "diversity": 185 },
                { "stage": "lMid", "diversity": 117 }, { "stage": "Tojo", "diversity": 162 }, { "stage": "Boto", "diversity": 265 },
                { "stage": "Atda", "diversity": 134 }, { "stage": "Tomm", "diversity": 0 }, { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Aves",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 4 },
                { "stage": "Plei", "diversity": 4 },
                { "stage": "Plio", "diversity": 5 },
                { "stage": "Mi", "diversity": 6 },
                { "stage": "Ol", "diversity": 7 },
                { "stage": "Eo", "diversity": 6 },
                { "stage": "Pale", "diversity": 3 },
                { "stage": "Maes", "diversity": 8 },
                { "stage": "Camp", "diversity": 3 },
                { "stage": "Sant", "diversity": 4 },
                { "stage": "Coni", "diversity": 2 },
                { "stage": "Turo", "diversity": 1 },
                { "stage": "Ceno", "diversity": 1 },
                { "stage": "Albi", "diversity": 1 },
                { "stage": "Apti", "diversity": 0 },
                { "stage": "Barr", "diversity": 0 },
                { "stage": "Haut", "diversity": 0 },
                { "stage": "Vala", "diversity": 0 },
                { "stage": "Berr", "diversity": 0 },
                { "stage": "Tith", "diversity": 0 },
                { "stage": "Kimm", "diversity": 0 },
                { "stage": "Oxfo", "diversity": 0 },
                { "stage": "Call", "diversity": 0 },
                { "stage": "Bath", "diversity": 0 },
                { "stage": "Bajo", "diversity": 0 },
                { "stage": "Aale", "diversity": 0 },
                { "stage": "Toar", "diversity": 0 },
                { "stage": "Plie", "diversity": 0 },
                { "stage": "Sine", "diversity": 0 },
                { "stage": "Hett", "diversity": 0 },
                { "stage": "Nori", "diversity": 0 },
                { "stage": "Carn", "diversity": 0 },
                { "stage": "Ladi", "diversity": 0 },
                { "stage": "Anis", "diversity": 0 },
                { "stage": "Olen", "diversity": 0 },
                { "stage": "Indu", "diversity": 0 },
                { "stage": "Tatr", "diversity": 0 },
                { "stage": "Guad", "diversity": 0 },
                { "stage": "Leon", "diversity": 0 },
                { "stage": "Sakm", "diversity": 0 },
                { "stage": "Asse", "diversity": 0 },
                { "stage": "Step", "diversity": 0 },
                { "stage": "Mosc", "diversity": 0 },
                { "stage": "Bash", "diversity": 0 },
                { "stage": "Serp", "diversity": 0 },
                { "stage": "Vise", "diversity": 0 },
                { "stage": "Tour", "diversity": 0 },
                { "stage": "Fame", "diversity": 0 },
                { "stage": "Fras", "diversity": 0 },
                { "stage": "Give", "diversity": 0 },
                { "stage": "Eife", "diversity": 0 },
                { "stage": "Emsi", "diversity": 0 },
                { "stage": "Sieg", "diversity": 0 },
                { "stage": "Gedi", "diversity": 0 },
                { "stage": "Prid", "diversity": 0 },
                { "stage": "Ludl", "diversity": 0 },
                { "stage": "Wenl", "diversity": 0 },
                { "stage": "Ldov", "diversity": 0 },
                { "stage": "Ashg", "diversity": 0 },
                { "stage": "Cara", "diversity": 0 },
                { "stage": "Llde", "diversity": 0 },
                { "stage": "Llvi", "diversity": 0 },
                { "stage": "Aren", "diversity": 0 },
                { "stage": "Trem", "diversity": 0 },
                { "stage": "Trep", "diversity": 0 },
                { "stage": "Fran", "diversity": 0 },
                { "stage": "Dres", "diversity": 0 },
                { "stage": "uMid", "diversity": 0 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 0 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Reptilia",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 4 },
                { "stage": "Plei", "diversity": 4 },
                { "stage": "Plio", "diversity": 6 },
                { "stage": "Mi", "diversity": 8 },
                { "stage": "Ol", "diversity": 10 },
                { "stage": "Eo", "diversity": 26 },
                { "stage": "Pale", "diversity": 8 },
                { "stage": "Maes", "diversity": 27 },
                { "stage": "Camp", "diversity": 25 },
                { "stage": "Sant", "diversity": 9 },
                { "stage": "Coni", "diversity": 7 },
                { "stage": "Turo", "diversity": 12 },
                { "stage": "Ceno", "diversity": 8 },
                { "stage": "Albi", "diversity": 5 },
                { "stage": "Apti", "diversity": 2 },
                { "stage": "Barr", "diversity": 1 },
                { "stage": "Haut", "diversity": 3 },
                { "stage": "Vala", "diversity": 3 },
                { "stage": "Berr", "diversity": 3 },
                { "stage": "Tith", "diversity": 17 },
                { "stage": "Kimm", "diversity": 12 },
                { "stage": "Oxfo", "diversity": 8 },
                { "stage": "Call", "diversity": 9 },
                { "stage": "Bath", "diversity": 6 },
                { "stage": "Bajo", "diversity": 4 },
                { "stage": "Aale", "diversity": 2 },
                { "stage": "Toar", "diversity": 12 },
                { "stage": "Plie", "diversity": 8 },
                { "stage": "Sine", "diversity": 7 },
                { "stage": "Hett", "diversity": 6 },
                { "stage": "Nori", "diversity": 9 },
                { "stage": "Carn", "diversity": 10 },
                { "stage": "Ladi", "diversity": 22 },
                { "stage": "Anis", "diversity": 20 },
                { "stage": "Olen", "diversity": 10 },
                { "stage": "Indu", "diversity": 0 },
                { "stage": "Tatr", "diversity": 0 },
                { "stage": "Guad", "diversity": 0 },
                { "stage": "Leon", "diversity": 1 },
                { "stage": "Sakm", "diversity": 0 },
                { "stage": "Asse", "diversity": 0 },
                { "stage": "Step", "diversity": 0 },
                { "stage": "Mosc", "diversity": 0 },
                { "stage": "Bash", "diversity": 0 },
                { "stage": "Serp", "diversity": 0 },
                { "stage": "Vise", "diversity": 0 },
                { "stage": "Tour", "diversity": 0 },
                { "stage": "Fame", "diversity": 0 },
                { "stage": "Fras", "diversity": 0 },
                { "stage": "Give", "diversity": 0 },
                { "stage": "Eife", "diversity": 0 },
                { "stage": "Emsi", "diversity": 0 },
                { "stage": "Sieg", "diversity": 0 },
                { "stage": "Gedi", "diversity": 0 },
                { "stage": "Prid", "diversity": 0 },
                { "stage": "Ludl", "diversity": 0 },
                { "stage": "Wenl", "diversity": 0 },
                { "stage": "Ldov", "diversity": 0 },
                { "stage": "Ashg", "diversity": 0 },
                { "stage": "Cara", "diversity": 0 },
                { "stage": "Llde", "diversity": 0 },
                { "stage": "Llvi", "diversity": 0 },
                { "stage": "Aren", "diversity": 0 },
                { "stage": "Trem", "diversity": 0 },
                { "stage": "Trep", "diversity": 0 },
                { "stage": "Fran", "diversity": 0 },
                { "stage": "Dres", "diversity": 0 },
                { "stage": "uMid", "diversity": 0 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 0 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },                
        {
            "name": "Mammalia",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 31 },
                { "stage": "Plei", "diversity": 36 },
                { "stage": "Plio", "diversity": 68 },
                { "stage": "Mi", "diversity": 198 },
                { "stage": "Ol", "diversity": 35 },
                { "stage": "Eo", "diversity": 28 },
                { "stage": "Pale", "diversity": 0 },
                { "stage": "Maes", "diversity": 0 },
                { "stage": "Camp", "diversity": 0 },
                { "stage": "Sant", "diversity": 0 },
                { "stage": "Coni", "diversity": 0 },
                { "stage": "Turo", "diversity": 0 },
                { "stage": "Ceno", "diversity": 0 },
                { "stage": "Albi", "diversity": 0 },
                { "stage": "Apti", "diversity": 0 },
                { "stage": "Barr", "diversity": 0 },
                { "stage": "Haut", "diversity": 0 },
                { "stage": "Vala", "diversity": 0 },
                { "stage": "Berr", "diversity": 0 },
                { "stage": "Tith", "diversity": 0 },
                { "stage": "Kimm", "diversity": 0 },
                { "stage": "Oxfo", "diversity": 0 },
                { "stage": "Call", "diversity": 0 },
                { "stage": "Bath", "diversity": 0 },
                { "stage": "Bajo", "diversity": 0 },
                { "stage": "Aale", "diversity": 0 },
                { "stage": "Toar", "diversity": 0 },
                { "stage": "Plie", "diversity": 0 },
                { "stage": "Sine", "diversity": 0 },
                { "stage": "Hett", "diversity": 0 },
                { "stage": "Nori", "diversity": 0 },
                { "stage": "Carn", "diversity": 0 },
                { "stage": "Ladi", "diversity": 0 },
                { "stage": "Anis", "diversity": 0 },
                { "stage": "Olen", "diversity": 0 },
                { "stage": "Indu", "diversity": 0 },
                { "stage": "Tatr", "diversity": 0 },
                { "stage": "Guad", "diversity": 0 },
                { "stage": "Leon", "diversity": 0 },
                { "stage": "Sakm", "diversity": 0 },
                { "stage": "Asse", "diversity": 0 },
                { "stage": "Step", "diversity": 0 },
                { "stage": "Mosc", "diversity": 0 },
                { "stage": "Bash", "diversity": 0 },
                { "stage": "Serp", "diversity": 0 },
                { "stage": "Vise", "diversity": 0 },
                { "stage": "Tour", "diversity": 0 },
                { "stage": "Fame", "diversity": 0 },
                { "stage": "Fras", "diversity": 0 },
                { "stage": "Give", "diversity": 0 },
                { "stage": "Eife", "diversity": 0 },
                { "stage": "Emsi", "diversity": 0 },
                { "stage": "Sieg", "diversity": 0 },
                { "stage": "Gedi", "diversity": 0 },
                { "stage": "Prid", "diversity": 0 },
                { "stage": "Ludl", "diversity": 0 },
                { "stage": "Wenl", "diversity": 0 },
                { "stage": "Ldov", "diversity": 0 },
                { "stage": "Ashg", "diversity": 0 },
                { "stage": "Cara", "diversity": 0 },
                { "stage": "Llde", "diversity": 0 },
                { "stage": "Llvi", "diversity": 0 },
                { "stage": "Aren", "diversity": 0 },
                { "stage": "Trem", "diversity": 0 },
                { "stage": "Trep", "diversity": 0 },
                { "stage": "Fran", "diversity": 0 },
                { "stage": "Dres", "diversity": 0 },
                { "stage": "uMid", "diversity": 0 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 0 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Amphibia",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 0 },
                { "stage": "Plei", "diversity": 0 },
                { "stage": "Plio", "diversity": 0 },
                { "stage": "Mi", "diversity": 0 },
                { "stage": "Ol", "diversity": 0 },
                { "stage": "Eo", "diversity": 0 },
                { "stage": "Pale", "diversity": 0 },
                { "stage": "Maes", "diversity": 0 },
                { "stage": "Camp", "diversity": 0 },
                { "stage": "Sant", "diversity": 0 },
                { "stage": "Coni", "diversity": 0 },
                { "stage": "Turo", "diversity": 0 },
                { "stage": "Ceno", "diversity": 0 },
                { "stage": "Albi", "diversity": 0 },
                { "stage": "Apti", "diversity": 0 },
                { "stage": "Barr", "diversity": 0 },
                { "stage": "Haut", "diversity": 0 },
                { "stage": "Vala", "diversity": 0 },
                { "stage": "Berr", "diversity": 0 },
                { "stage": "Tith", "diversity": 0 },
                { "stage": "Kimm", "diversity": 0 },
                { "stage": "Oxfo", "diversity": 0 },
                { "stage": "Call", "diversity": 0 },
                { "stage": "Bath", "diversity": 0 },
                { "stage": "Bajo", "diversity": 0 },
                { "stage": "Aale", "diversity": 0 },
                { "stage": "Toar", "diversity": 0 },
                { "stage": "Plie", "diversity": 0 },
                { "stage": "Sine", "diversity": 0 },
                { "stage": "Hett", "diversity": 0 },
                { "stage": "Nori", "diversity": 0 },
                { "stage": "Carn", "diversity": 0 },
                { "stage": "Ladi", "diversity": 0 },
                { "stage": "Anis", "diversity": 0 },
                { "stage": "Olen", "diversity": 0 },
                { "stage": "Indu", "diversity": 1 },
                { "stage": "Tatr", "diversity": 0 },
                { "stage": "Guad", "diversity": 0 },
                { "stage": "Leon", "diversity": 0 },
                { "stage": "Sakm", "diversity": 0 },
                { "stage": "Asse", "diversity": 0 },
                { "stage": "Step", "diversity": 0 },
                { "stage": "Mosc", "diversity": 0 },
                { "stage": "Bash", "diversity": 0 },
                { "stage": "Serp", "diversity": 0 },
                { "stage": "Vise", "diversity": 0 },
                { "stage": "Tour", "diversity": 0 },
                { "stage": "Fame", "diversity": 0 },
                { "stage": "Fras", "diversity": 0 },
                { "stage": "Give", "diversity": 0 },
                { "stage": "Eife", "diversity": 0 },
                { "stage": "Emsi", "diversity": 0 },
                { "stage": "Sieg", "diversity": 0 },
                { "stage": "Gedi", "diversity": 0 },
                { "stage": "Prid", "diversity": 0 },
                { "stage": "Ludl", "diversity": 0 },
                { "stage": "Wenl", "diversity": 0 },
                { "stage": "Ldov", "diversity": 0 },
                { "stage": "Ashg", "diversity": 0 },
                { "stage": "Cara", "diversity": 0 },
                { "stage": "Llde", "diversity": 0 },
                { "stage": "Llvi", "diversity": 0 },
                { "stage": "Aren", "diversity": 0 },
                { "stage": "Trem", "diversity": 0 },
                { "stage": "Trep", "diversity": 0 },
                { "stage": "Fran", "diversity": 0 },
                { "stage": "Dres", "diversity": 0 },
                { "stage": "uMid", "diversity": 0 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 0 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Gastropoda",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 1526 },
                { "stage": "Plei", "diversity": 1541 },
                { "stage": "Plio", "diversity": 1619 },
                { "stage": "Mi", "diversity": 1691 },
                { "stage": "Ol", "diversity": 1151 },
                { "stage": "Eo", "diversity": 1211 },
                { "stage": "Pale", "diversity": 575 },
                { "stage": "Maes", "diversity": 381 },
                { "stage": "Camp", "diversity": 341 },
                { "stage": "Sant", "diversity": 233 },
                { "stage": "Coni", "diversity": 224 },
                { "stage": "Turo", "diversity": 206 },
                { "stage": "Ceno", "diversity": 195 },
                { "stage": "Albi", "diversity": 178 },
                { "stage": "Apti", "diversity": 147 },
                { "stage": "Barr", "diversity": 127 },
                { "stage": "Haut", "diversity": 108 },
                { "stage": "Vala", "diversity": 111 },
                { "stage": "Berr", "diversity": 106 },
                { "stage": "Tith", "diversity": 129 },
                { "stage": "Kimm", "diversity": 134 },
                { "stage": "Oxfo", "diversity": 138 },
                { "stage": "Call", "diversity": 122 },
                { "stage": "Bath", "diversity": 137 },
                { "stage": "Bajo", "diversity": 136 },
                { "stage": "Aale", "diversity": 94 },
                { "stage": "Toar", "diversity": 89 },
                { "stage": "Plie", "diversity": 95 },
                { "stage": "Sine", "diversity": 92 },
                { "stage": "Hett", "diversity": 68 },
                { "stage": "Nori", "diversity": 134 },
                { "stage": "Carn", "diversity": 148 },
                { "stage": "Ladi", "diversity": 195 },
                { "stage": "Anis", "diversity": 84 },
                { "stage": "Olen", "diversity": 55 },
                { "stage": "Indu", "diversity": 45 },
                { "stage": "Tatr", "diversity": 91 },
                { "stage": "Guad", "diversity": 140 },
                { "stage": "Leon", "diversity": 135 },
                { "stage": "Sakm", "diversity": 114 },
                { "stage": "Asse", "diversity": 112 },
                { "stage": "Step", "diversity": 113 },
                { "stage": "Mosc", "diversity": 115 },
                { "stage": "Bash", "diversity": 98 },
                { "stage": "Serp", "diversity": 115 },
                { "stage": "Vise", "diversity": 120 },
                { "stage": "Tour", "diversity": 88 },
                { "stage": "Fame", "diversity": 70 },
                { "stage": "Fras", "diversity": 86 },
                { "stage": "Give", "diversity": 109 },
                { "stage": "Eife", "diversity": 125 },
                { "stage": "Emsi", "diversity": 113 },
                { "stage": "Sieg", "diversity": 103 },
                { "stage": "Gedi", "diversity": 75 },
                { "stage": "Prid", "diversity": 70 },
                { "stage": "Ludl", "diversity": 108 },
                { "stage": "Wenl", "diversity": 85 },
                { "stage": "Ldov", "diversity": 65 },
                { "stage": "Ashg", "diversity": 72 },
                { "stage": "Cara", "diversity": 67 },
                { "stage": "Llde", "diversity": 41 },
                { "stage": "Llvi", "diversity": 39 },
                { "stage": "Aren", "diversity": 43 },
                { "stage": "Trem", "diversity": 31 },
                { "stage": "Trep", "diversity": 13 },
                { "stage": "Fran", "diversity": 2 },
                { "stage": "Dres", "diversity": 3 },
                { "stage": "uMid", "diversity": 1 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 0 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Bivalvia",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 815 },
                { "stage": "Plei", "diversity": 825 },
                { "stage": "Plio", "diversity": 874 },
                { "stage": "Mi", "diversity": 887 },
                { "stage": "Ol", "diversity": 601 },
                { "stage": "Eo", "diversity": 615 },
                { "stage": "Pale", "diversity": 289 },
                { "stage": "Maes", "diversity": 413 },
                { "stage": "Camp", "diversity": 351 },
                { "stage": "Sant", "diversity": 281 },
                { "stage": "Coni", "diversity": 257 },
                { "stage": "Turo", "diversity": 258 },
                { "stage": "Ceno", "diversity": 278 },
                { "stage": "Albi", "diversity": 235 },
                { "stage": "Apti", "diversity": 215 },
                { "stage": "Barr", "diversity": 170 },
                { "stage": "Haut", "diversity": 156 },
                { "stage": "Vala", "diversity": 146 },
                { "stage": "Berr", "diversity": 136 },
                { "stage": "Tith", "diversity": 176 },
                { "stage": "Kimm", "diversity": 163 },
                { "stage": "Oxfo", "diversity": 157 },
                { "stage": "Call", "diversity": 144 },
                { "stage": "Bath", "diversity": 150 },
                { "stage": "Bajo", "diversity": 138 },
                { "stage": "Aale", "diversity": 119 },
                { "stage": "Toar", "diversity": 115 },
                { "stage": "Plie", "diversity": 119 },
                { "stage": "Sine", "diversity": 98 },
                { "stage": "Hett", "diversity": 88 },
                { "stage": "Nori", "diversity": 118 },
                { "stage": "Carn", "diversity": 112 },
                { "stage": "Ladi", "diversity": 83 },
                { "stage": "Anis", "diversity": 60 },
                { "stage": "Olen", "diversity": 39 },
                { "stage": "Indu", "diversity": 30 },
                { "stage": "Tatr", "diversity": 59 },
                { "stage": "Guad", "diversity": 108 },
                { "stage": "Leon", "diversity": 106 },
                { "stage": "Sakm", "diversity": 73 },
                { "stage": "Asse", "diversity": 60 },
                { "stage": "Step", "diversity": 64 },
                { "stage": "Mosc", "diversity": 62 },
                { "stage": "Bash", "diversity": 53 },
                { "stage": "Serp", "diversity": 60 },
                { "stage": "Vise", "diversity": 58 },
                { "stage": "Tour", "diversity": 45 },
                { "stage": "Fame", "diversity": 35 },
                { "stage": "Fras", "diversity": 42 },
                { "stage": "Give", "diversity": 39 },
                { "stage": "Eife", "diversity": 37 },
                { "stage": "Emsi", "diversity": 43 },
                { "stage": "Sieg", "diversity": 37 },
                { "stage": "Gedi", "diversity": 36 },
                { "stage": "Prid", "diversity": 40 },
                { "stage": "Ludl", "diversity": 57 },
                { "stage": "Wenl", "diversity": 64 },
                { "stage": "Ldov", "diversity": 34 },
                { "stage": "Ashg", "diversity": 66 },
                { "stage": "Cara", "diversity": 65 },
                { "stage": "Llde", "diversity": 39 },
                { "stage": "Llvi", "diversity": 32 },
                { "stage": "Aren", "diversity": 36 },
                { "stage": "Trem", "diversity": 2 },
                { "stage": "Trep", "diversity": 0 },
                { "stage": "Fran", "diversity": 0 },
                { "stage": "Dres", "diversity": 0 },
                { "stage": "uMid", "diversity": 0 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 1 },
                { "stage": "Tojo", "diversity": 1 },
                { "stage": "Boto", "diversity": 2 },
                { "stage": "Atda", "diversity": 2 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Arthropoda",
            "type": "phylum",
            "diversity_data": [
                { "stage": "R", "diversity": 426 },
                { "stage": "Plei", "diversity": 446 },
                { "stage": "Plio", "diversity": 457 },
                { "stage": "Mi", "diversity": 505 },
                { "stage": "Ol", "diversity": 357 },
                { "stage": "Eo", "diversity": 394 },
                { "stage": "Pale", "diversity": 216 },
                { "stage": "Maes", "diversity": 236 },
                { "stage": "Camp", "diversity": 208 },
                { "stage": "Sant", "diversity": 189 },
                { "stage": "Coni", "diversity": 160 },
                { "stage": "Turo", "diversity": 159 },
                { "stage": "Ceno", "diversity": 180 },
                { "stage": "Albi", "diversity": 159 },
                { "stage": "Apti", "diversity": 118 },
                { "stage": "Barr", "diversity": 106 },
                { "stage": "Haut", "diversity": 96 },
                { "stage": "Vala", "diversity": 87 },
                { "stage": "Berr", "diversity": 72 },
                { "stage": "Tith", "diversity": 106 },
                { "stage": "Kimm", "diversity": 77 },
                { "stage": "Oxfo", "diversity": 78 },
                { "stage": "Call", "diversity": 82 },
                { "stage": "Bath", "diversity": 79 },
                { "stage": "Bajo", "diversity": 63 },
                { "stage": "Aale", "diversity": 44 },
                { "stage": "Toar", "diversity": 49 },
                { "stage": "Plie", "diversity": 50 },
                { "stage": "Sine", "diversity": 44 },
                { "stage": "Hett", "diversity": 35 },
                { "stage": "Nori", "diversity": 40 },
                { "stage": "Carn", "diversity": 33 },
                { "stage": "Ladi", "diversity": 33 },
                { "stage": "Anis", "diversity": 34 },
                { "stage": "Olen", "diversity": 27 },
                { "stage": "Indu", "diversity": 13 },
                { "stage": "Tatr", "diversity": 81 },
                { "stage": "Guad", "diversity": 70 },
                { "stage": "Leon", "diversity": 70 },
                { "stage": "Sakm", "diversity": 71 },
                { "stage": "Asse", "diversity": 72 },
                { "stage": "Step", "diversity": 85 },
                { "stage": "Mosc", "diversity": 108 },
                { "stage": "Bash", "diversity": 101 },
                { "stage": "Serp", "diversity": 130 },
                { "stage": "Vise", "diversity": 167 },
                { "stage": "Tour", "diversity": 158 },
                { "stage": "Fame", "diversity": 162 },
                { "stage": "Fras", "diversity": 150 },
                { "stage": "Give", "diversity": 217 },
                { "stage": "Eife", "diversity": 286 },
                { "stage": "Emsi", "diversity": 347 },
                { "stage": "Sieg", "diversity": 258 },
                { "stage": "Gedi", "diversity": 248 },
                { "stage": "Prid", "diversity": 221 },
                { "stage": "Ludl", "diversity": 239 },
                { "stage": "Wenl", "diversity": 270 },
                { "stage": "Ldov", "diversity": 213 },
                { "stage": "Ashg", "diversity": 383 },
                { "stage": "Cara", "diversity": 563 },
                { "stage": "Llde", "diversity": 397 },
                { "stage": "Llvi", "diversity": 325 },
                { "stage": "Aren", "diversity": 298 },
                { "stage": "Trem", "diversity": 232 },
                { "stage": "Trep", "diversity": 222 },
                { "stage": "Fran", "diversity": 291 },
                { "stage": "Dres", "diversity": 300 },
                { "stage": "uMid", "diversity": 316 },
                { "stage": "mMid", "diversity": 254 },
                { "stage": "lMid", "diversity": 150 },
                { "stage": "Tojo", "diversity": 192 },
                { "stage": "Boto", "diversity": 295 },
                { "stage": "Atda", "diversity": 197 },
                { "stage": "Tomm", "diversity": 2 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Chordata",
            "type": "phylum",
            "diversity_data": [
                { "stage": "R", "diversity": 601 },
                { "stage": "Plei", "diversity": 612 },
                { "stage": "Plio", "diversity": 632 },
                { "stage": "Mi", "diversity": 765 },
                { "stage": "Ol", "diversity": 448 },
                { "stage": "Eo", "diversity": 529 },
                { "stage": "Pale", "diversity": 145 },
                { "stage": "Maes", "diversity": 129 },
                { "stage": "Camp", "diversity": 153 },
                { "stage": "Sant", "diversity": 135 },
                { "stage": "Coni", "diversity": 102 },
                { "stage": "Turo", "diversity": 116 },
                { "stage": "Ceno", "diversity": 176 },
                { "stage": "Albi", "diversity": 65 },
                { "stage": "Apti", "diversity": 50 },
                { "stage": "Barr", "diversity": 28 },
                { "stage": "Haut", "diversity": 31 },
                { "stage": "Vala", "diversity": 31 },
                { "stage": "Berr", "diversity": 34 },
                { "stage": "Tith", "diversity": 91 },
                { "stage": "Kimm", "diversity": 70 },
                { "stage": "Oxfo", "diversity": 54 },
                { "stage": "Call", "diversity": 49 },
                { "stage": "Bath", "diversity": 42 },
                { "stage": "Bajo", "diversity": 36 },
                { "stage": "Aale", "diversity": 32 },
                { "stage": "Toar", "diversity": 54 },
                { "stage": "Plie", "diversity": 32 },
                { "stage": "Sine", "diversity": 42 },
                { "stage": "Hett", "diversity": 29 },
                { "stage": "Nori", "diversity": 60 },
                { "stage": "Carn", "diversity": 58 },
                { "stage": "Ladi", "diversity": 74 },
                { "stage": "Anis", "diversity": 53 },
                { "stage": "Olen", "diversity": 41 },
                { "stage": "Indu", "diversity": 26 },
                { "stage": "Tatr", "diversity": 21 },
                { "stage": "Guad", "diversity": 23 },
                { "stage": "Leon", "diversity": 26 },
                { "stage": "Sakm", "diversity": 13 },
                { "stage": "Asse", "diversity": 15 },
                { "stage": "Step", "diversity": 24 },
                { "stage": "Mosc", "diversity": 59 },
                { "stage": "Bash", "diversity": 36 },
                { "stage": "Serp", "diversity": 62 },
                { "stage": "Vise", "diversity": 70 },
                { "stage": "Tour", "diversity": 77 },
                { "stage": "Fame", "diversity": 94 },
                { "stage": "Fras", "diversity": 136 },
                { "stage": "Give", "diversity": 78 },
                { "stage": "Eife", "diversity": 61 },
                { "stage": "Emsi", "diversity": 63 },
                { "stage": "Sieg", "diversity": 59 },
                { "stage": "Gedi", "diversity": 84 },
                { "stage": "Prid", "diversity": 53 },
                { "stage": "Ludl", "diversity": 42 },
                { "stage": "Wenl", "diversity": 43 },
                { "stage": "Ldov", "diversity": 27 },
                { "stage": "Ashg", "diversity": 40 },
                { "stage": "Cara", "diversity": 65 },
                { "stage": "Llde", "diversity": 49 },
                { "stage": "Llvi", "diversity": 53 },
                { "stage": "Aren", "diversity": 57 },
                { "stage": "Trem", "diversity": 42 },
                { "stage": "Trep", "diversity": 13 },
                { "stage": "Fran", "diversity": 6 },
                { "stage": "Dres", "diversity": 4 },
                { "stage": "uMid", "diversity": 3 },
                { "stage": "mMid", "diversity": 4 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 1 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },
        {
            "name": "Cnidaria",
            "type": "phylum",
            "diversity_data": [
                { "stage": "R", "diversity": 171 },
                { "stage": "Plei", "diversity": 174 },
                { "stage": "Plio", "diversity": 179 },
                { "stage": "Mi", "diversity": 216 },
                { "stage": "Ol", "diversity": 174 },
                { "stage": "Eo", "diversity": 170 },
                { "stage": "Pale", "diversity": 114 },
                { "stage": "Maes", "diversity": 115 },
                { "stage": "Camp", "diversity": 98 },
                { "stage": "Sant", "diversity": 101 },
                { "stage": "Coni", "diversity": 87 },
                { "stage": "Turo", "diversity": 96 },
                { "stage": "Ceno", "diversity": 93 },
                { "stage": "Albi", "diversity": 72 },
                { "stage": "Apti", "diversity": 87 },
                { "stage": "Barr", "diversity": 78 },
                { "stage": "Haut", "diversity": 64 },
                { "stage": "Vala", "diversity": 62 },
                { "stage": "Berr", "diversity": 62 },
                { "stage": "Tith", "diversity": 90 },
                { "stage": "Kimm", "diversity": 93 },
                { "stage": "Oxfo", "diversity": 88 },
                { "stage": "Call", "diversity": 59 },
                { "stage": "Bath", "diversity": 64 },
                { "stage": "Bajo", "diversity": 49 },
                { "stage": "Aale", "diversity": 31 },
                { "stage": "Toar", "diversity": 34 },
                { "stage": "Plie", "diversity": 48 },
                { "stage": "Sine", "diversity": 37 },
                { "stage": "Hett", "diversity": 31 },
                { "stage": "Nori", "diversity": 76 },
                { "stage": "Carn", "diversity": 47 },
                { "stage": "Ladi", "diversity": 28 },
                { "stage": "Anis", "diversity": 20 },
                { "stage": "Olen", "diversity": 3 },
                { "stage": "Indu", "diversity": 2 },
                { "stage": "Tatr", "diversity": 39 },
                { "stage": "Guad", "diversity": 73 },
                { "stage": "Leon", "diversity": 74 },
                { "stage": "Sakm", "diversity": 77 },
                { "stage": "Asse", "diversity": 76 },
                { "stage": "Step", "diversity": 81 },
                { "stage": "Mosc", "diversity": 93 },
                { "stage": "Bash", "diversity": 89 },
                { "stage": "Serp", "diversity": 105 },
                { "stage": "Vise", "diversity": 178 },
                { "stage": "Tour", "diversity": 107 },
                { "stage": "Fame", "diversity": 80 },
                { "stage": "Fras", "diversity": 126 },
                { "stage": "Give", "diversity": 193 },
                { "stage": "Eife", "diversity": 251 },
                { "stage": "Emsi", "diversity": 188 },
                { "stage": "Sieg", "diversity": 126 },
                { "stage": "Gedi", "diversity": 123 },
                { "stage": "Prid", "diversity": 88 },
                { "stage": "Ludl", "diversity": 152 },
                { "stage": "Wenl", "diversity": 174 },
                { "stage": "Ldov", "diversity": 159 },
                { "stage": "Ashg", "diversity": 140 },
                { "stage": "Cara", "diversity": 93 },
                { "stage": "Llde", "diversity": 23 },
                { "stage": "Llvi", "diversity": 14 },
                { "stage": "Aren", "diversity": 10 },
                { "stage": "Trem", "diversity": 6 },
                { "stage": "Trep", "diversity": 4 },
                { "stage": "Fran", "diversity": 3 },
                { "stage": "Dres", "diversity": 5 },
                { "stage": "uMid", "diversity": 5 },
                { "stage": "mMid", "diversity": 11 },
                { "stage": "lMid", "diversity": 6 },
                { "stage": "Tojo", "diversity": 4 },
                { "stage": "Boto", "diversity": 15 },
                { "stage": "Atda", "diversity": 6 },
                { "stage": "Tomm", "diversity": 6 },
                { "stage": "N-Da", "diversity": 3 }
            ]
        },
        {
            "name": "Mollusca",
            "type": "phylum",
            "diversity_data": [
                { "stage": "R", "diversity": 2403 },
                { "stage": "Plei", "diversity": 2429 },
                { "stage": "Plio", "diversity": 2550 },
                { "stage": "Mi", "diversity": 2637 },
                { "stage": "Ol", "diversity": 1797 },
                { "stage": "Eo", "diversity": 1870 },
                { "stage": "Pale", "diversity": 885 },
                { "stage": "Maes", "diversity": 879 },
                { "stage": "Camp", "diversity": 816 },
                { "stage": "Sant", "diversity": 612 },
                { "stage": "Coni", "diversity": 586 },
                { "stage": "Turo", "diversity": 582 },
                { "stage": "Ceno", "diversity": 619 },
                { "stage": "Albi", "diversity": 614 },
                { "stage": "Apti", "diversity": 486 },
                { "stage": "Barr", "diversity": 402 },
                { "stage": "Haut", "diversity": 349 },
                { "stage": "Vala", "diversity": 345 },
                { "stage": "Berr", "diversity": 309 },
                { "stage": "Tith", "diversity": 458 },
                { "stage": "Kimm", "diversity": 411 },
                { "stage": "Oxfo", "diversity": 420 },
                { "stage": "Call", "diversity": 422 },
                { "stage": "Bath", "diversity": 399 },
                { "stage": "Bajo", "diversity": 411 },
                { "stage": "Aale", "diversity": 295 },
                { "stage": "Toar", "diversity": 330 },
                { "stage": "Plie", "diversity": 307 },
                { "stage": "Sine", "diversity": 278 },
                { "stage": "Hett", "diversity": 191 },
                { "stage": "Nori", "diversity": 398 },
                { "stage": "Carn", "diversity": 400 },
                { "stage": "Ladi", "diversity": 382 },
                { "stage": "Anis", "diversity": 277 },
                { "stage": "Olen", "diversity": 221 },
                { "stage": "Indu", "diversity": 106 },
                { "stage": "Tatr", "diversity": 203 },
                { "stage": "Guad", "diversity": 341 },
                { "stage": "Leon", "diversity": 358 },
                { "stage": "Sakm", "diversity": 270 },
                { "stage": "Asse", "diversity": 247 },
                { "stage": "Step", "diversity": 272 },
                { "stage": "Mosc", "diversity": 266 },
                { "stage": "Bash", "diversity": 261 },
                { "stage": "Serp", "diversity": 305 },
                { "stage": "Vise", "diversity": 314 },
                { "stage": "Tour", "diversity": 206 },
                { "stage": "Fame", "diversity": 306 },
                { "stage": "Fras", "diversity": 260 },
                { "stage": "Give", "diversity": 270 },
                { "stage": "Eife", "diversity": 299 },
                { "stage": "Emsi", "diversity": 285 },
                { "stage": "Sieg", "diversity": 221 },
                { "stage": "Gedi", "diversity": 173 },
                { "stage": "Prid", "diversity": 185 },
                { "stage": "Ludl", "diversity": 295 },
                { "stage": "Wenl", "diversity": 298 },
                { "stage": "Ldov", "diversity": 173 },
                { "stage": "Ashg", "diversity": 283 },
                { "stage": "Cara", "diversity": 292 },
                { "stage": "Llde", "diversity": 227 },
                { "stage": "Llvi", "diversity": 227 },
                { "stage": "Aren", "diversity": 274 },
                { "stage": "Trem", "diversity": 119 },
                { "stage": "Trep", "diversity": 89 },
                { "stage": "Fran", "diversity": 23 },
                { "stage": "Dres", "diversity": 26 },
                { "stage": "uMid", "diversity": 25 },
                { "stage": "mMid", "diversity": 21 },
                { "stage": "lMid", "diversity": 24 },
                { "stage": "Tojo", "diversity": 24 },
                { "stage": "Boto", "diversity": 36 },
                { "stage": "Atda", "diversity": 50 },
                { "stage": "Tomm", "diversity": 93 },
                { "stage": "N-Da", "diversity": 15 }
            ]
        },
        {
            "name": "Porifera",
            "type": "phylum",
            "diversity_data": [
                { "stage": "R", "diversity": 52 },
                { "stage": "Plei", "diversity": 54 },
                { "stage": "Plio", "diversity": 40 },
                { "stage": "Mi", "diversity": 61 },
                { "stage": "Ol", "diversity": 47 },
                { "stage": "Eo", "diversity": 51 },
                { "stage": "Pale", "diversity": 41 },
                { "stage": "Maes", "diversity": 66 },
                { "stage": "Camp", "diversity": 121 },
                { "stage": "Sant", "diversity": 100 },
                { "stage": "Coni", "diversity": 89 },
                { "stage": "Turo", "diversity": 91 },
                { "stage": "Ceno", "diversity": 104 },
                { "stage": "Albi", "diversity": 93 },
                { "stage": "Apti", "diversity": 72 },
                { "stage": "Barr", "diversity": 45 },
                { "stage": "Haut", "diversity": 44 },
                { "stage": "Vala", "diversity": 47 },
                { "stage": "Berr", "diversity": 42 },
                { "stage": "Tith", "diversity": 61 },
                { "stage": "Kimm", "diversity": 86 },
                { "stage": "Oxfo", "diversity": 86 },
                { "stage": "Call", "diversity": 53 },
                { "stage": "Bath", "diversity": 41 },
                { "stage": "Bajo", "diversity": 43 },
                { "stage": "Aale", "diversity": 31 },
                { "stage": "Toar", "diversity": 26 },
                { "stage": "Plie", "diversity": 26 },
                { "stage": "Sine", "diversity": 24 },
                { "stage": "Hett", "diversity": 25 },
                { "stage": "Nori", "diversity": 70 },
                { "stage": "Carn", "diversity": 85 },
                { "stage": "Ladi", "diversity": 38 },
                { "stage": "Anis", "diversity": 31 },
                { "stage": "Olen", "diversity": 27 },
                { "stage": "Indu", "diversity": 26 },
                { "stage": "Tatr", "diversity": 53 },
                { "stage": "Guad", "diversity": 71 },
                { "stage": "Leon", "diversity": 61 },
                { "stage": "Sakm", "diversity": 32 },
                { "stage": "Asse", "diversity": 30 },
                { "stage": "Step", "diversity": 26 },
                { "stage": "Mosc", "diversity": 26 },
                { "stage": "Bash", "diversity": 24 },
                { "stage": "Serp", "diversity": 18 },
                { "stage": "Vise", "diversity": 33 },
                { "stage": "Tour", "diversity": 20 },
                { "stage": "Fame", "diversity": 40 },
                { "stage": "Fras", "diversity": 85 },
                { "stage": "Give", "diversity": 65 },
                { "stage": "Eife", "diversity": 73 },
                { "stage": "Emsi", "diversity": 57 },
                { "stage": "Sieg", "diversity": 54 },
                { "stage": "Gedi", "diversity": 52 },
                { "stage": "Prid", "diversity": 53 },
                { "stage": "Ludl", "diversity": 81 },
                { "stage": "Wenl", "diversity": 74 },
                { "stage": "Ldov", "diversity": 44 },
                { "stage": "Ashg", "diversity": 65 },
                { "stage": "Cara", "diversity": 84 },
                { "stage": "Llde", "diversity": 36 },
                { "stage": "Llvi", "diversity": 26 },
                { "stage": "Aren", "diversity": 15 },
                { "stage": "Trem", "diversity": 13 },
                { "stage": "Trep", "diversity": 8 },
                { "stage": "Fran", "diversity": 8 },
                { "stage": "Dres", "diversity": 13 },
                { "stage": "uMid", "diversity": 18 },
                { "stage": "mMid", "diversity": 25 },
                { "stage": "lMid", "diversity": 14 },
                { "stage": "Tojo", "diversity": 35 },
                { "stage": "Boto", "diversity": 279 },
                { "stage": "Atda", "diversity": 165 },
                { "stage": "Tomm", "diversity": 22 },
                { "stage": "N-Da", "diversity": 1 }
            ]
        },                                        
        {
            "name": "Arachnida",
            "type": "class",
            "diversity_data": [
                { "stage": "R", "diversity": 0 },
                { "stage": "Plei", "diversity": 0 },
                { "stage": "Plio", "diversity": 0 },
                { "stage": "Mi", "diversity": 0 },
                { "stage": "Ol", "diversity": 0 },
                { "stage": "Eo", "diversity": 0 },
                { "stage": "Pale", "diversity": 0 },
                { "stage": "Maes", "diversity": 0 },
                { "stage": "Camp", "diversity": 0 },
                { "stage": "Sant", "diversity": 0 },
                { "stage": "Coni", "diversity": 0 },
                { "stage": "Turo", "diversity": 0 },
                { "stage": "Ceno", "diversity": 0 },
                { "stage": "Albi", "diversity": 0 },
                { "stage": "Apti", "diversity": 0 },
                { "stage": "Barr", "diversity": 0 },
                { "stage": "Haut", "diversity": 0 },
                { "stage": "Vala", "diversity": 0 },
                { "stage": "Berr", "diversity": 0 },
                { "stage": "Tith", "diversity": 0 },
                { "stage": "Kimm", "diversity": 0 },
                { "stage": "Oxfo", "diversity": 0 },
                { "stage": "Call", "diversity": 0 },
                { "stage": "Bath", "diversity": 0 },
                { "stage": "Bajo", "diversity": 0 },
                { "stage": "Aale", "diversity": 0 },
                { "stage": "Toar", "diversity": 0 },
                { "stage": "Plie", "diversity": 0 },
                { "stage": "Sine", "diversity": 0 },
                { "stage": "Hett", "diversity": 0 },
                { "stage": "Nori", "diversity": 0 },
                { "stage": "Carn", "diversity": 0 },
                { "stage": "Ladi", "diversity": 0 },
                { "stage": "Anis", "diversity": 0 },
                { "stage": "Olen", "diversity": 0 },
                { "stage": "Indu", "diversity": 0 },
                { "stage": "Tatr", "diversity": 0 },
                { "stage": "Guad", "diversity": 0 },
                { "stage": "Leon", "diversity": 0 },
                { "stage": "Sakm", "diversity": 0 },
                { "stage": "Asse", "diversity": 0 },
                { "stage": "Step", "diversity": 0 },
                { "stage": "Mosc", "diversity": 2 },
                { "stage": "Bash", "diversity": 0 },
                { "stage": "Serp", "diversity": 0 },
                { "stage": "Vise", "diversity": 0 },
                { "stage": "Tour", "diversity": 0 },
                { "stage": "Fame", "diversity": 0 },
                { "stage": "Fras", "diversity": 0 },
                { "stage": "Give", "diversity": 0 },
                { "stage": "Eife", "diversity": 0 },
                { "stage": "Emsi", "diversity": 0 },
                { "stage": "Sieg", "diversity": 0 },
                { "stage": "Gedi", "diversity": 0 },
                { "stage": "Prid", "diversity": 1 },
                { "stage": "Ludl", "diversity": 0 },
                { "stage": "Wenl", "diversity": 1 },
                { "stage": "Ldov", "diversity": 1 },
                { "stage": "Ashg", "diversity": 0 },
                { "stage": "Cara", "diversity": 0 },
                { "stage": "Llde", "diversity": 0 },
                { "stage": "Llvi", "diversity": 0 },
                { "stage": "Aren", "diversity": 0 },
                { "stage": "Trem", "diversity": 0 },
                { "stage": "Trep", "diversity": 0 },
                { "stage": "Fran", "diversity": 0 },
                { "stage": "Dres", "diversity": 0 },
                { "stage": "uMid", "diversity": 0 },
                { "stage": "mMid", "diversity": 0 },
                { "stage": "lMid", "diversity": 0 },
                { "stage": "Tojo", "diversity": 0 },
                { "stage": "Boto", "diversity": 0 },
                { "stage": "Atda", "diversity": 0 },
                { "stage": "Tomm", "diversity": 0 },
                { "stage": "N-Da", "diversity": 0 }
            ]
        },                                        
        {
            "name": "Brachiopoda",
            "type": "class",
            "diversity_data": [
                { "stage": "Cambriano", "diversity": 100 }, { "stage": "Ordoviciano", "diversity": 150 },
                { "stage": "Siluriano", "diversity": 200 }, { "stage": "Devoniano", "diversity": 180 },
                { "stage": "Carbonífero", "diversity": 150 }, { "stage": "Permiano", "diversity": 80 },
                { "stage": "Triássico", "diversity": 50 }, { "stage": "Jurássico", "diversity": 60 },
                { "stage": "Cretáceo", "diversity": 70 }, { "stage": "Paleogeno", "diversity": 80 },
                { "stage": "Neogeno", "diversity": 90 }, { "stage": "Quaternário", "diversity": 100 }
            ]
        },
        {
            "name": "Ammonoidea",
            "type": "class",
            "diversity_data": [
                { "stage": "Cambriano", "diversity": 0 }, { "stage": "Ordoviciano", "diversity": 0 },
                { "stage": "Siluriano", "diversity": 0 }, { "stage": "Devoniano", "diversity": 10 },
                { "stage": "Carbonífero", "diversity": 50 }, { "stage": "Permiano", "diversity": 120 },
                { "stage": "Triássico", "diversity": 150 }, { "stage": "Jurássico", "diversity": 200 },
                { "stage": "Cretáceo", "diversity": 180 }, { "stage": "Paleogeno", "diversity": 0 },
                { "stage": "Neogeno", "diversity": 0 }, { "stage": "Quaternário", "diversity": 0 }
            ]
        }
    ]
};

// Função para buscar e carregar os dados (agora da constante)
function loadData() {
    return PALEODATA.paleodata;
}

// Função para popular a área de checkboxes
function populateCheckboxes() {
    const data = loadData();
    data.forEach((group, index) => {
        const label = document.createElement('label');
        label.className = 'checkbox-item';
        label.htmlFor = `group-${index}`;

        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.id = `group-${index}`;
        checkbox.value = group.name;

        const customCheckbox = document.createElement('div');
        customCheckbox.className = 'checkbox-custom';

        const span = document.createElement('span');
        span.textContent = `${group.name} (${group.type})`;

        label.appendChild(checkbox);
        label.appendChild(customCheckbox);
        label.appendChild(span);
        checkboxesContainer.appendChild(label);
    });
}

// Função para verificar o número de checkboxes selecionados
function handleCheckboxChange() {
    const checkedCount = document.querySelectorAll('#group-checkboxes input:checked').length;
    const allCheckboxes = document.querySelectorAll('#group-checkboxes input[type="checkbox"]');

    if (checkedCount >= 5) {
        allCheckboxes.forEach(checkbox => {
            if (!checkbox.checked) {
                checkbox.disabled = true;
            }
        });
    } else {
        allCheckboxes.forEach(checkbox => {
            checkbox.disabled = false;
        });
    }
}

// Função para atualizar o gráfico com base na seleção do usuário
function updateChart() {
    const data = loadData();
    const selectedOptions = Array.from(document.querySelectorAll('#group-checkboxes input:checked')).map(checkbox => checkbox.value);

    // Mapeamento dos estágios para os rótulos de tempo
    const timeLabels = data.length > 0 ? data[0].diversity_data.map(d => TIME_DATA_MYA[d.stage] || d.stage).reverse() : [];

    const datasets = data
        .filter(group => selectedOptions.includes(group.name))
        .map(group => {
            const stages = group.diversity_data.map(d => d.stage).reverse();
            const diversities = group.diversity_data.map(d => d.diversity).reverse();

            return {
                label: group.name,
                data: diversities,
                borderColor: getRandomColor(),
                fill: false,
                tension: 0.2
            };
        });

    if (myChart) {
        myChart.destroy();
    }

    myChart = new Chart(chartCanvas, {
        type: 'line',
        data: {
            labels: timeLabels, // Usando os valores numéricos no eixo X
            datasets: datasets
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                x: {
                    title: {
                        display: true,
                        text: 'Tempo (milhões de anos)' // Alterando o título do eixo
                    }
                },
                y: {
                    title: {
                        display: true,
                        text: 'Diversidade (Número de Gêneros)'
                    },
                    beginAtZero: true
                }
            },
            plugins: {
                tooltip: {
                    mode: 'index',
                    intersect: false,
                    callbacks: {
                        title: function(tooltipItems) {
                            // Encontra o estágio correspondente à idade no eixo X para exibir no tooltip
                            const stageValue = tooltipItems[0].label;
                            const stageName = Object.keys(TIME_DATA_MYA).find(key => String(TIME_DATA_MYA[key]) === stageValue);
                            return stageName ? `${stageName} (${stageValue} mya)` : `${stageValue} mya`;
                        }
                    }
                }
            }
        }
    });
}

// Função auxiliar para gerar cores hexadecimais aleatórias
function getRandomColor() {
    const letters = '0123456789ABCDEF';
    let color = '#';
    for (let i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

// Adiciona os event listeners
document.addEventListener('DOMContentLoaded', populateCheckboxes);
checkboxesContainer.addEventListener('change', handleCheckboxChange);
updateButton.addEventListener('click', updateChart);